
package pricinggateway;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.oracle.communications.pricing.ObjectFactory;
import com.oracle.communications.pricing.PDCResponseType;
import com.oracle.communications.pricing.PricingInputXMLType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "pricingGatewayPortType", targetNamespace = "urn:PricingGateWay")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PricingGatewayPortType {


    /**
     * 
     * @param param
     * @return
     *     returns com.oracle.communications.pricing.PDCResponseType
     * @throws PricingExceptionResponse
     */
    @WebMethod(action = "urn:PricingGateWay/createPricing")
    @WebResult(name = "PDCResponse", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "return")
    public PDCResponseType createPricing(
        @WebParam(name = "CreatePricingInputXML", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "param")
        PricingInputXMLType param)
        throws PricingExceptionResponse
    ;

    /**
     * 
     * @param param
     * @return
     *     returns com.oracle.communications.pricing.PDCResponseType
     * @throws PricingExceptionResponse
     */
    @WebMethod(action = "urn:PricingGateWay/modifyPricing")
    @WebResult(name = "PDCResponse", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "return")
    public PDCResponseType modifyPricing(
        @WebParam(name = "UpdatePricingInputXML", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "param")
        PricingInputXMLType param)
        throws PricingExceptionResponse
    ;

    /**
     * 
     * @param param
     * @return
     *     returns com.oracle.communications.pricing.PDCResponseType
     * @throws PricingExceptionResponse
     */
    @WebMethod(action = "urn:PricingGateWay/createPricingAndSubmit")
    @WebResult(name = "PDCResponse", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "return")
    public PDCResponseType createPricingAndSubmit(
        @WebParam(name = "CreatePublishPricingInputXML", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "param")
        PricingInputXMLType param)
        throws PricingExceptionResponse
    ;

    /**
     * 
     * @param param
     * @return
     *     returns com.oracle.communications.pricing.PDCResponseType
     * @throws PricingExceptionResponse
     */
    @WebMethod(action = "urn:PricingGateWay/modifyPricingAndSubmit")
    @WebResult(name = "PDCResponse", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "return")
    public PDCResponseType modifyPricingAndSubmit(
        @WebParam(name = "UpdatePublishPricingInputXML", targetNamespace = "http://www.oracle.com/communications/pricing", partName = "param")
        PricingInputXMLType param)
        throws PricingExceptionResponse
    ;

}
