
package pricinggateway;

import javax.xml.ws.WebFault;
import com.oracle.communications.pricing.PricingExceptionType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "PricingException", targetNamespace = "http://www.oracle.com/communications/pricing")
public class PricingExceptionResponse
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private PricingExceptionType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public PricingExceptionResponse(String message, PricingExceptionType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public PricingExceptionResponse(String message, PricingExceptionType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.communications.pricing.PricingExceptionType
     */
    public PricingExceptionType getFaultInfo() {
        return faultInfo;
    }

}
